# Generated by Django 6.0.3 on 2026-03-24 11:59

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Aktivitet',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('navn', models.CharField(max_length=200)),
                ('beskrivelse', models.TextField()),
                ('dato', models.DateField()),
                ('sted', models.CharField(max_length=200)),
                ('opprettet', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'ordering': ['-dato'],
            },
        ),
        migrations.CreateModel(
            name='Medlem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('navn', models.CharField(max_length=100)),
                ('epost', models.EmailField(max_length=254, unique=True)),
                ('telefon', models.CharField(max_length=20)),
                ('medlemsdato', models.DateField(auto_now_add=True)),
                ('aktiv', models.BooleanField(default=True)),
            ],
            options={
                'ordering': ['navn'],
            },
        ),
        migrations.CreateModel(
            name='Betaling',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('belop', models.DecimalField(decimal_places=2, max_digits=8)),
                ('betalingsdato', models.DateField()),
                ('status', models.CharField(choices=[('betalt', 'Betalt'), ('ikke_betalt', 'Ikke betalt')], default='ikke_betalt', max_length=20)),
                ('medlem', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='products.medlem')),
            ],
            options={
                'ordering': ['-betalingsdato'],
            },
        ),
        migrations.CreateModel(
            name='Pamelding',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('dato_pameldt', models.DateField(auto_now_add=True)),
                ('aktivitet', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='products.aktivitet')),
                ('medlem', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='products.medlem')),
            ],
            options={
                'unique_together': {('medlem', 'aktivitet')},
            },
        ),
    ]
